apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newapplication
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Arastusharma/mongo-config.git
    targetRevision: HEAD
    path: Mongo
  destination: 
    server: https://kubernetes.default.svc
    namespace: mongoapplication

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
